// Between Mirror — the exported demo data is published to a website, so it is held to the same
// standard as the site itself: nothing about the machine that produced it, and nothing that phones
// anywhere.
//
// The first export of `/api/data/overview` carried `R:\proj\app\examples\demo.db` — the
// maintainer's drive letter and directory layout, headed for a public page about privacy. That is the
// whole reason this file exists: the export is generated by machine from a real database, so whatever
// the API truthfully reports about the local filesystem is what gets published unless something
// stops it.
import { describe, it, expect } from 'vitest';
import { readFileSync, readdirSync, existsSync } from 'node:fs';
import { join, resolve, extname } from 'node:path';
import { redactPaths, urlKey, slugFor } from '../src/cli/demo-export';

const DIR = resolve(__dirname, '../../site/demo-data');
const files = existsSync(DIR) ? readdirSync(DIR).filter((f) => extname(f) === '.json') : [];

describe('the exported demo data says nothing about the machine that built it', () => {
  it('has actually been exported', () => {
    expect(files.length, 'run `npm run demo:export`').toBeGreaterThan(10);
    expect(files).toContain('manifest.json');
  });

  it('contains no absolute filesystem path from any real machine', () => {
    const bad: string[] = [];
    for (const f of files) {
      const text = readFileSync(join(DIR, f), 'utf8');
      // A Windows drive root, or a real POSIX home that is not the generic placeholder.
      for (const m of text.matchAll(/[A-Za-z]:[\\/][^"]*/g)) bad.push(`${f}: ${m[0]}`);
      for (const m of text.matchAll(/\/(?:Users|home)\/(?!you\/Between)[^"]*/g)) bad.push(`${f}: ${m[0]}`);
    }
    expect(bad, `a real filesystem path would be published:\n  ${bad.join('\n  ')}`).toEqual([]);
  });

  it('contains no URL to anywhere', () => {
    // The demo must be able to run with the network unplugged. A URL in the DATA is as much an egress
    // path as a URL in the markup, and nothing else was checking this half.
    const bad: string[] = [];
    for (const f of files) {
      const text = readFileSync(join(DIR, f), 'utf8');
      for (const m of text.matchAll(/(?:https?:)?\/\/[a-z0-9.-]+\.[a-z]{2,}/gi)) bad.push(`${f}: ${m[0]}`);
    }
    expect(bad, `the demo data references an external origin:\n  ${bad.join('\n  ')}`).toEqual([]);
  });

  it('every manifest entry names a file that exists, and every file is reachable', () => {
    // TWO manifests: reads keyed by URL, and the handful of read-shaped POSTs (Ask's planner) keyed by
    // URL plus exact body. Checking only the first reported the Ask captures as orphans — correctly,
    // by its own lights, which is what the orphan half of this test is for.
    const manifest = JSON.parse(readFileSync(join(DIR, 'manifest.json'), 'utf8')) as Record<string, string>;
    const posts = JSON.parse(readFileSync(join(DIR, 'posts.json'), 'utf8')) as Record<string, string>;

    const missing = [...Object.entries(manifest), ...Object.entries(posts)]
      .filter(([, slug]) => !files.includes(slug));
    expect(missing, 'a manifest points at files that were not written').toEqual([]);

    // The reverse: an orphan file is data the shim can never serve, which means it was exported for
    // nothing and will rot without anyone noticing.
    const named = new Set([
      ...Object.values(manifest), ...Object.values(posts),
      'manifest.json', 'posts.json', 'questions.json',
    ]);
    const orphans = files.filter((f) => !named.has(f));
    expect(orphans, 'exported files no manifest entry points at').toEqual([]);
  });

  it('offers only questions it holds a captured answer for', () => {
    // The chips and the answers come from the same export, and this is what keeps them from drifting:
    // a question offered with no captured plan behind it would hit the shim's refusal and look broken.
    const questions = JSON.parse(readFileSync(join(DIR, 'questions.json'), 'utf8')) as string[];
    const posts = JSON.parse(readFileSync(join(DIR, 'posts.json'), 'utf8')) as Record<string, string>;
    expect(questions.length, 'the demo should offer a few questions').toBeGreaterThan(0);

    const unanswerable = questions.filter(
      (q) => !Object.keys(posts).some((k) => k.includes(JSON.stringify({ query: q, filters: {} }))),
    );
    expect(unanswerable, 'a question is offered with no captured answer behind it').toEqual([]);
  });

  it('shows the tool declining as well as answering', () => {
    // A demo where every question succeeds teaches the wrong thing about an instrument whose whole
    // claim is that it stops when the words run out. At least one offered question must decline.
    const posts = JSON.parse(readFileSync(join(DIR, 'posts.json'), 'utf8')) as Record<string, string>;
    const plans = Object.values(posts).map((slug) => JSON.parse(readFileSync(join(DIR, slug), 'utf8')) as { sufficient: boolean });
    expect(plans.some((p) => p.sufficient), 'at least one question should be answered').toBe(true);
    expect(plans.some((p) => !p.sufficient), 'at least one question should honestly decline').toBe(true);
  });

  it('exports the surfaces the demo actually needs', () => {
    const manifest = JSON.parse(readFileSync(join(DIR, 'manifest.json'), 'utf8')) as Record<string, string>;
    for (const key of ['/api/threads', '/api/threads/1/episodes', '/api/threads/1/metrics',
      '/api/threads/1/trajectory', '/api/threads/1/findings', '/api/data/overview']) {
      expect(Object.keys(manifest), `${key} is missing from the demo export`).toContain(key);
    }
  });
});

describe('every receipt the demo cites resolves to a message the demo can show', () => {
  // The demo's entire argument is that a claim without its receipt is a horoscope. A demo whose
  // receipts pointed at nothing would be exactly the failure it exists to disprove — and worse than
  // no demo, because a visitor clicking "the words underneath" and getting an empty panel learns that
  // the guarantee is decorative.
  //
  // This is checked against the EXPORTED transcript rather than the database, because the exported
  // transcript is what the demo actually has. A receipt resolving in demo.db and not in the captured
  // messages is a broken demo that passes a database check.

  const load = (slug: string): unknown => JSON.parse(readFileSync(join(DIR, slug), 'utf8'));

  it('resolves every evidence id cited in every frozen reading', () => {
    const manifest = JSON.parse(readFileSync(join(DIR, 'manifest.json'), 'utf8')) as Record<string, string>;

    // Every message id the demo can actually display, from the captured transcript.
    const available = new Set<number>();
    for (const [key, slug] of Object.entries(manifest)) {
      if (!/\/messages(\?|$)/.test(key)) continue;
      const payload = load(slug) as { messages?: { id: number }[] } | { id: number }[];
      const rows = Array.isArray(payload) ? payload : payload.messages ?? [];
      for (const m of rows) available.add(m.id);
    }
    expect(available.size, 'the demo transcript should not be empty').toBeGreaterThan(100);

    const dangling: string[] = [];
    let checked = 0;
    for (const [key, slug] of Object.entries(manifest)) {
      if (!/reflections/.test(key)) continue;
      const payload = load(slug) as unknown;
      const readings = Array.isArray(payload) ? payload : [payload];
      for (const reading of readings as { id?: number; claims?: { id: string; evidenceIds?: number[] }[] }[]) {
        for (const claim of reading.claims ?? []) {
          for (const eid of claim.evidenceIds ?? []) {
            checked++;
            if (!available.has(eid)) dangling.push(`${key} reading ${reading.id} claim ${claim.id} → message ${eid}`);
          }
        }
      }
    }

    // A pass over zero receipts is not a pass. If the demo ever stops shipping a frozen reading, this
    // says so rather than going quietly green.
    expect(checked, 'the demo should ship at least one receipted claim').toBeGreaterThan(0);
    expect(dangling, `a demo receipt points at a message the demo cannot show:\n  ${dangling.join('\n  ')}`).toEqual([]);
  });
});

describe('the export helpers', () => {
  it('normalises query order so one URL has one key', () => {
    expect(urlKey('/api/x?b=2&a=1')).toBe(urlKey('/api/x?a=1&b=2'));
    expect(urlKey('/api/x')).toBe('/api/x');
  });

  it('turns a key into a collision-free filename', () => {
    expect(slugFor('/api/threads/1/episodes')).toBe('threads_1_episodes.json');
    expect(slugFor('/api/threads/1')).not.toBe(slugFor('/api/threads/1/episodes'));
  });

  it('redacts a Windows repo root but keeps what is below it', () => {
    const body = JSON.stringify({ dbPath: 'I:\\claude\\between\\examples\\demo.db' });
    const out = redactPaths(body, 'I:\\claude\\between');
    expect(out).toContain('/home/you/Between/examples/demo.db');
    expect(out).not.toMatch(/I:/);
  });

  it('redacts an unrelated absolute path it has never seen', () => {
    const body = JSON.stringify({ a: 'D:\\somewhere\\else.db', b: '/Users/someone/thing' });
    const out = redactPaths(body, 'I:\\claude\\between');
    expect(out).not.toMatch(/D:/);
    expect(out).not.toMatch(/someone/);
  });

  it('does not collapse distinct paths onto one another', () => {
    // The first fix was greedy and turned five different directories into the same string, which
    // made the Settings panel look broken while technically being "redacted".
    const body = JSON.stringify({
      dbPath: 'I:\\r\\demo.db', dataDir: 'I:\\r\\data', backupsDir: 'I:\\r\\backups',
    });
    const out = JSON.parse(redactPaths(body, 'I:\\r')) as Record<string, string>;
    expect(new Set(Object.values(out)).size).toBe(3);
  });
});
